apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: bets-http-log
config:
  http_endpoint: http://fluentd.logs:9880
  method: POST
  timeout: 1000
  keepalive: 1000
  flush_timeout: 2
  retry_count: 15
plugin: http-log