name: Test API Contract

on:
  - pull_request

jobs:
  build:
    name: Check OpenAPI Contract
    runs-on: ubuntu-latest
    services:
      mock:
        image: stoplight/prism:latest
        options: --entrypoint prism mock assets/api-docs/bets-api.yaml
        ports:
          - 4010:4010

    steps:
      # Check out the repository
      - uses: actions/checkout@v2

      - uses: matt-ball/newman-action@master
        with:
          collection: assets/api-tests/bets.postman.json